"""Добавлен столбец

Revision ID: 462a06737ff2
Revises: 7f5dc1e0120b
Create Date: 2025-03-18 19:29:23.870479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462a06737ff2'
down_revision: Union[str, None] = '7f5dc1e0120b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'telegram_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('place_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'places', ['place_id'], ['id'])
    op.add_column('employees', sa.Column('telegram_id', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
